### ISSUE TITLE
Medians missing with pip.ado

### ISSUE THREAD

**Issue by danielmahler** [worldbank/pip#28]
Hi all,

I'm in the process of preparing our annual data submission for SDG 10.2.1 (share living below half the median) and noticed that there are a few missing medians returned through the pip.ado

pip, country(all) year(all)
keep if missing(median)

Most of these were also missing in povcalnet.ado. In noticed that Argentina has missing medians now, though, which it didn't before. It would be nice not to have any missings, but perhaps this is not the greatest problem on your to-do list.

**Comment by Tefera19** [comment]
Hi @randrescastaneda

Could there be a reason why median are missing for chn, gnb, gtm, guy, idn, ind, nam, sle, and slv at national level estimates? I noticed that the median estimates are calculated for rural/urban level for the specified years.

Tefera

**Comment by danielmahler** [comment]
But how can we calculate poverty rates for the countries where the estimates of the regressions are invalid?

**Comment by randrescastaneda** [comment]
Fair question. Following the old practice of Povcalnet, PIP selects distributional stats and poverty stats with different but complementary algorithms. In the case of SLV 1989, for instance, the algorithm says that neither of the Lorenz parametrizations is valid for dist stats. Yet, only the Lorenz Beta is used for poverty Stats because it meets normality, whereas the quadratic does not meet normality. This is why we have estimates for poverty but not for distribution. It is an old practice that I am not sure if it should be revisited. 

The functions of the algorithm can be found in the [gd_select_lorenz.R](https://github.com/PIP-Technical-Team/wbpip/blob/dev/R/gd_select_lorenz.R) file of the {wbpip} package. In production, we use the function [prod_gd_select_lorenz](https://github.com/PIP-Technical-Team/wbpip/blob/dev/R/prod_gd_select_lorenz.R), which uses the function `retrieve_poverty()`. If you want, we could talk about it in detail over Teams. 

Feel free to close the issue if you think my answer is enough to leave it at this point. 

Best,
